// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfICMEZpGa1vEZyahYd0XY2hTeqiluvs',
    appId: '1:828463848493:web:ba53892729be78961caca4',
    messagingSenderId: '828463848493',
    projectId: 'rido-4fb08',
    authDomain: 'rido-4fb08.firebaseapp.com',
    storageBucket: 'rido-4fb08.appspot.com',
    measurementId: 'G-L31M82Y0MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMvH9NcopwkFDYzhz16fwTjszTPyMnxxA',
    appId: '1:828463848493:android:31b37adb466581331caca4',
    messagingSenderId: '828463848493',
    projectId: 'rido-4fb08',
    storageBucket: 'rido-4fb08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSRxbgZIiWCE7lG5nqpp52-ZOBrLqe58',
    appId: '1:828463848493:ios:7dbdfef6884a46401caca4',
    messagingSenderId: '828463848493',
    projectId: 'rido-4fb08',
    storageBucket: 'rido-4fb08.appspot.com',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBSRxbgZIiWCE7lG5nqpp52-ZOBrLqe58',
    appId: '1:828463848493:ios:7dbdfef6884a46401caca4',
    messagingSenderId: '828463848493',
    projectId: 'rido-4fb08',
    storageBucket: 'rido-4fb08.appspot.com',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqfICMEZpGa1vEZyahYd0XY2hTeqiluvs',
    appId: '1:828463848493:web:2e6ce071419a71161caca4',
    messagingSenderId: '828463848493',
    projectId: 'rido-4fb08',
    authDomain: 'rido-4fb08.firebaseapp.com',
    storageBucket: 'rido-4fb08.appspot.com',
    measurementId: 'G-8DLCTC6Q0D',
  );
}
